site_name: NijkerkerveenRP Server regels
theme:
  name: material

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: ichte modus
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Donkere modus


nav:
  - Server regels: index.md
  - Discord: 'https://discord.gg/NQn8Y7uyKZ'
  - Home: 'https://nijkerkerveenrp.github.io/'
# Extensions
